name: Custom Build

on:
  workflow_dispatch:
    inputs:
      cn:
        description: 'Include Chinese version (add "--cn" to build args)'
        required: false
        default: false
        type: boolean
      normal:
        description: 'Remove opinionated features (add "--normal" to build args)'
        required: false
        default: false
        type: boolean
      no_liga:
        description: 'Remove ligatures (add "--no-liga" to build args)'
        required: false
        default: false
        type: boolean
      no_hinted:
        description: 'Build unhinted font (add "--no-hinted" to build args)'
        required: false
        default: false
        type: boolean
      nf_mono:
        description: 'Fixed Nerd Font icon width (add "--nf-mono" to build args)'
        required: false
        default: false
        type: boolean
      feat:
        description: 'Enable features, split by `,`, e.g. "cv01,ss02" (add "--feat feat1,feat2" to build args)'
        required: false
        default: ''
        type: string
      build_args:
        description: 'Other args for build.py'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  custom-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: './requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          # https://github.com/ryanoasis/nerd-fonts/blob/b3c1b0cf424ac32915cf4fd822c3938d4a815566/.github/workflows/release.yml#L144-L166
          if [[ "${{ github.event.inputs.build_args }}" == *"--font-patcher"* ]] || python build.py --dry | jq -e '.nerd_font.use_font_patcher == true' >/dev/null; then
            sudo apt update -y -q
            sudo apt install software-properties-common -y -q
            sudo apt install python3-fontforge -y -q
            sudo apt install fuse -y -q

            curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" --output fontforge
            chmod u+x fontforge
            echo Try appimage
            ./fontforge --version
            export PATH=`pwd`:$PATH
            echo "PATH=$PATH" >> $GITHUB_ENV
            echo Try appimage with path
            fontforge --version
          fi

      - name: Run custom script
        run: |
          build_args="--archive"
          if [ "${{ github.event.inputs.cn }}" == "true" ]; then
            build_args="$build_args --cn"
          fi
          if [ "${{ github.event.inputs.normal }}" == "true" ]; then
            build_args="$build_args --normal"
          fi
          if [ "${{ github.event.inputs.no_liga }}" == "true" ]; then
            build_args="$build_args --no-liga"
          fi
          if [ "${{ github.event.inputs.no_hinted }}" == "true" ]; then
            build_args="$build_args --no-hinted"
          fi
          if [ "${{ github.event.inputs.nf_mono }}" == "true" ]; then
            build_args="$build_args --nf-mono"
          fi
          if [ -n "${{ github.event.inputs.feat }}" ]; then
            build_args="$build_args --feat ${{ github.event.inputs.feat }}"
          fi
          if [ -n "${{ github.event.inputs.build_args }}" ]; then
            build_args="$build_args ${{ github.event.inputs.build_args }}"
          fi

          echo "BUILD_ARGS=$build_args" >> $GITHUB_ENV
          python build.py $build_args
        continue-on-error: true
      - id: check_issue
        name: Check issue feature file
        run: |
          if [ -f fonts/issue.fea ]
          then
            echo 'exists=true' >> $GITHUB_OUTPUT
          else
            echo 'exists=false' >> $GITHUB_OUTPUT
          fi
      - name: Upload issue artifact
        if: ${{ steps.check_issue.outputs.exists == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: issue-fea-file
          path: fonts/issue.fea
      - name: Create release
        run: |
          if [ ! -d "fonts/archive" ]; then
            echo "Error: Failed to build font, please check [Run custom script] step."
            exit 1
          fi
          echo "### Build arguments" >> NOTES
          echo "\`\`\`" >> NOTES
          echo "python build.py $BUILD_ARGS" >> NOTES
          echo "\`\`\`" >> NOTES
          echo "### Final Configuration" >> NOTES
          echo "\`\`\`" >> NOTES
          python build.py $BUILD_ARGS --dry | sed '1s/^/font_config: /' >> NOTES
          echo "\`\`\`" >> NOTES
          gh release create "v$(date +%s)" fonts/archive/*.* --notes-file NOTES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
